- name: Copy default nginx site config file
  become: yes
  ansible.builtin.template:
    src: default.conf
    dest:  /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: '0644'
  notify:
  - Restart nginx

- name: Install swagger ui dist
  become: yes
  ansible.builtin.unarchive:
    src: swagger-ui-dist.tgz
    dest: /var/www/html
    creates: /var/www/html/swagger-ui-bundle.js

- name: Replace default swagger ui URL in all files
  become: yes
  with_items:
  - swagger-initializer.js
  - swagger-ui-bundle.js
  - swagger-ui-es-bundle-core.js
  - swagger-ui-es-bundle.js
  - swagger-ui-standalone-preset.js
  - swagger-ui.js
  ansible.builtin.replace:
    path: "/var/www/html/{{ item }}"
    regexp: "https://petstore.swagger.io/v2/swagger.json"
    replace: "{{ postgrest_url }}/auth"

- name: Change ownership of swagger ui
  become: yes
  ansible.builtin.file:
    dest: /var/www/html
    owner: www-data
    group: www-data
    state: directory
    recurse: yes
