- name: Disable apache service
  become: yes
  ansible.builtin.systemd:
    name: apache2
    state: stopped
    enabled: no
  # In case the seervice actually does not exist
  ignore_errors: yes

- name: Enable nginx service
  become: yes
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
