# Este es el password que se pone al superusuario "postgres"
postgresql_password: "Chang3m3!"
# Este es el password que se pone al usuario "pgAdmin4"
pgadmin4_password: "Chang3m3!"
# Este es el password que se pone al usuario "authenticator" de postgrest
postgrest_password: "Chang3m3!"
# Bases de datos iniciales para la config del sistema
postgresql_dbs:
  - name: "{{ pgadmin4_database }}"
    schemas:
    - "{{ pgadmin4_schema }}"
    user: "{{ pgadmin4_user }}"
    password: "{{ pgadmin4_password }}"
# Base de datos y schemas a los que postgrest proporciona acceso
postgrest_dbs:
- name: rivas
  api_port: "3001"
  schemas:
  - terceros
# Clave de firma de los JWT. 
postgrest_jwt_key: reallySafeAndSecureJWTSigningKey1234
