# Este es el password que se pone al superusuario "postgres"
postgresql_password: "Chang3m3!"
# Este es el password que se pone al usuario "pgAdmin4"
pgadmin4_password: "Chang3m3!"
# Este es el password que se pone al usuario "authenticator" de postgrest
postgrest_password: Chang3m3!
# Esta es la base de datos que se crea para pgAdmin
postgresql_dbs:
  # Base de datos para la config de pgAdmin4
  - name: pgadmin4
    schemas:
    - pgadmin4
    user: pgadmin4
    password: "Chang3m3!"
# Clave de firma de los JWT. 
postgrest_jwt_key: reallySafeAndSecureJWTSigningKey1234
