---
postgresql_version: "16"
postgrest_version: "v11.2.1"
postgrest_url: https://172.17.121.37/api
postgresql_host: "{{ hostvars['srvbbddunicadb1']['ansible_default_ipv4']['address'] }}"
postgresql_port: 5432
# Settings de pgadmin4
pgadmin4_database: system
pgadmin4_schema: pgadmin4
pgadmin4_user: pgadmin4
# Settings de postgrest
postgrest_database: "{{ pgadmin4_database }}"
postgrest_schema: api
postgrest_api_port: "3000"
postgrest_authenticator_role: authenticator
postgrest_anon_role: web_anon
# Modo de acceso a la API: follow-privileges / ignore-privileges
openapi_mode: follow-privileges
# Base de datos a crear para postgrest
postgrest_dbs:
- bbddunicarivas
- terceros
- territorios
- empleados
# Rutas de api, y combinaciones de bbdd + schemas a las que dan acceso
# NOTA: el path "auth" está reservado para la base de datos de login
postgrest_alias:
- database: bbddunicarivas
  path: bbddunicarivas
  api_port: "3001"
  schemas:
  - bd_territorios
  - bd_terceros
  - bd_empleados
  - cat_territorios
  - cat_terceros
  - cat_empleados
  - cat_global
  - public
- database: terceros
  path: terceros
  api_port: "3002"
  schemas:
  - public
- database: territorios
  path: territorios
  api_port: "3003"
  schemas:
  - catalogos
  - geo
  - meta
- database: empleados
  path: empleados
  api_port: "3004"
  schemas:
  - public
