- name: Create postgrest group
  become: yes
  ansible.builtin.group:
    name: postgrest
    state: present
    system: yes

- name: Create postgrest user
  become: yes
  ansible.builtin.user:
    name: postgrest
    group: postgrest
    state: present
    home: /etc/postgrest
    system: yes

- name: Create postgrest directory
  become: yes
  ansible.builtin.file:
    dest: /etc/postgrest
    state: directory
    owner: postgrest
    group: postgrest
    mode: '0500'

- name: Create postgrest auth config file
  become: yes
  ansible.builtin.template:
    src: postgrest_auth.conf
    dest: /etc/postgrest/postgrest_auth.conf
    owner: postgrest
    group: postgrest
    mode: '0400'
  notify:
  - Restart postgrest

- name: Create custom config files
  become: yes
  loop: "{{ postgrest_dbs }}"
  ansible.builtin.template:
    src: "postgrest.conf"
    dest: "/etc/postgrest/postgrest_{{ item.name }}.conf"
    owner: postgrest
    group: postgrest
    mode: '0400'
  notify:
  - Restart postgrest
