- name: Copy postgresql config files
  become: yes
  with_items:
  - postgresql.conf
  - pg_hba.conf
  ansible.builtin.copy:
    src: "{{ item }}"
    dest:  "/etc/postgresql/{{ postgresql_version }}/main/{{ item }}"
    owner: postgres
    group: postgres
    mode: '0644'
  notify:
  - Restart postgresql
