- name: Install python3 psycopg2 and acl
  package:
    name:
    - python3-psycopg2
    - acl
    state: present
  become: yes

- name: Set postgresql superuser password
  become_user: postgres
  become: yes
  community.postgresql.postgresql_user:
    db: postgres
    name: postgres
    password: "{{ postgresql_password }}"

- name: Create database owners
  with_items: "{{ postgresql_dbs }}"
  become_user: postgres
  become: yes
  community.postgresql.postgresql_user:
    name: "{{ item.user }}"
    password: "{{ item.password }}"

- name: Create databases
  with_items: "{{ postgresql_dbs }}"
  become_user: postgres
  become: yes
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.user }}"
    state: present
    template: template0

- name: Create schemas
  loop: "{{ postgresql_dbs | subelements('schemas') }}"
  become_user: postgres
  become: yes
  community.postgresql.postgresql_schema:
    database: "{{ item.0.name }}"
    name: "{{ item.1 }}"
    owner: "{{ item.0.user }}"
    state: present
