- name: Install postgresql-common
  package:
    name: postgresql-common
    state: present
  become: yes

- name: Add pgdg repository
  become: yes
  ansible.builtin.command: /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
  args:
    creates: /etc/apt/sources.list.d/pgdg.list

- name: Install postgresql packages
  package:
    name:
    - "postgresql-{{ postgresql_version }}"
    - "postgresql-{{ postgresql_version }}-postgis"
    state: present
  become: yes

- name: Install python3 psycopg2 and acl
  package:
    name:
    - python3-psycopg2
    - acl
    state: present
  become: yes
