- name: Create redis config file
  become: yes
  ansible.builtin.template:
    src: redis.conf
    dest: /etc/redis/redis.conf
    owner: redis
    group: redis
    mode: '0640'
  notify:
  - Restart redis
  