- name: "CREATE DATABASE {{ postgrest_dbs | join(',') }}"
  become_user: postgres
  become: yes
  loop: "{{ postgrest_dbs }}"
  community.postgresql.postgresql_db:
    name: "{{ item }}"
    owner: postgres
    state: present
    template: template0

- name: "CREATE SCHEMAS"
  loop: "{{ postgrest_alias | subelements('schemas') }}"
  become_user: postgres
  become: yes
  community.postgresql.postgresql_schema:
    database: "{{ item.0.database }}"
    name: "{{ item.1 }}"
    owner: postgres
    state: present

- name: "Grant USAGE ON SCHEMA TO {{ postgrest_anon_role }}"
  loop: "{{ postgrest_alias }}"
  become_user: postgres
  become: yes
  community.postgresql.postgresql_privs:
    database: "{{ item.database }}"
    state: present
    privs: USAGE
    type: schema
    objs: "{{ item.schemas | join(',') }}"
    roles: "{{ postgrest_anon_role }}"
