# Install the public key for the repository (if not done previously):
- name: Add PGP key for pgadmin repository
  become: yes
  ansible.builtin.shell: curl -fsS https://www.pgadmin.org/static/packages_pgadmin_org.pub | gpg --dearmor -o /usr/share/keyrings/packages-pgadmin-org.gpg
  args:
    creates: /usr/share/keyrings/packages-pgadmin-org.gpg

- name: Add deb repo file for pgadmin
  become: yes
  ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/packages-pgadmin-org.gpg] https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/$(lsb_release -cs) pgadmin4 main" > /etc/apt/sources.list.d/pgadmin4.list
  args:
    creates: /etc/apt/sources.list.d/pgadmin4.list
  register: pgadmin_repo

- name: Update cache
  ansible.builtin.apt:
    update_cache: yes
  become: yes
  when: pgadmin_repo is not skipped

- name: Install pgadmin4, uwsgi, uwsgi-plugin-python3
  package:
    name:
    - uwsgi
    - uwsgi-plugin-python3
    - pgadmin4
    state: present
  become: yes
