- name: Prepare backend servers
  hosts: backend
  roles:
  - postgresql_backend
  - postgrest_backend
  - couchdb_backend
  - minio_backend

- name: Prepare frontend servers
  hosts: frontend
  roles:
  - nginx_frontend
  - postgrest_frontend
  - pgadmin_frontend
  - redis_frontend
  - docker_frontend
