- name: Prepare backend servers
  hosts: backend
  roles:
  - postgresql_backend
  - postgrest_backend
  - couchdb_backend
  - minio_backend

- name: Prepare frontend servers
  hosts: frontend
  roles:
  - nginx_frontend
  - postgrest_frontend
  - pgadmin_frontend
  # NOTA: finalmente no usamos el rol de redis,
  # preferimos dejarlo dentro del docker-compose de budibase
  # por simplicidad. No es necesario hacer backups de este
  # redis, es un almacén de sesiones.
  - redis_frontend
  - docker_frontend
  - budibase_frontend
